DirectPV Operator: Add icon data (#852)
### Objective:

To add icon data because is needed by certification process:

```
Errors:[
	Error: Value : (minio-directpv-operator-rhmp.v4.0.7)
        csv.Spec.Icon elements should contain both data and mediatype
]
```

### Additional information:

* I am using the same image as in MinIO Operator:
[icon](https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/blob/main/operators/minio-operator-rhmp/5.0.9/manifests/minio-operator-rhmp.clusterserviceversion.yaml#L150)
* Originated from: [rhmp
pr](https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/pull/560)