Correcting the Operator example (#866)
### Objective:

To correct our Operator's example.

### Issue:

```sh
$ oc apply -f my-directpv.yaml 
error: resource mapping not found for name: "directpvchart-sample" namespace: "" from "my-directpv.yaml": no matches for kind "DirectpvChart" in version "charts.quay.io/v1alpha1"
ensure CRDs are installed first
```

### Solution:

Change from `DirectpvChart` to `DirectPVChart`

### Testing:

```sh
$ oc apply -f my-directpv.yaml 
directpvchart.charts.quay.io/directpvchart-sample created
```